version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '80:80'
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend